// rv32i_decode — constraint-synthesized by ConstraintCompiler
// Do not edit: regenerate with synth_compare.py

module rv32i_decode (
    input  logic [31:0]  instr,
    output logic [3:0]  alu_op,
    output logic [2:0]  imm_sel,
    output logic        use_rs1,
    output logic        use_rs2,
    output logic        use_rd,
    output logic        is_load,
    output logic        is_store,
    output logic        is_branch,
    output logic        is_jal,
    output logic        is_jalr,
    output logic [1:0]  mem_width,
    output logic        mem_signed
);

    // Generated by ConstraintCompiler — 40 blocks, 3 support bits
    wire [6:0] in_6_0 = instr[6:0];
    wire [2:0] in_14_12 = instr[14:12];
    wire in_30_30 = instr[30];
    wire w_sh0 = (~in_6_0[2] & in_6_0[4] & ~in_14_12[0] & in_14_12[1] & ~in_14_12[2]);
    wire w_sh1 = (~in_6_0[2] & ~in_6_0[4] & in_6_0[6] & ~in_14_12[2]);
    wire w_sh2 = (~in_6_0[2] & in_6_0[6] & ~in_14_12[1] & in_14_12[2]);
    wire w_sh3 = (in_6_0[2] & in_6_0[5] & ~in_6_0[6]);
    wire w_sh4 = (~in_6_0[4] & in_6_0[5] & ~in_6_0[6]);
    wire w_sh5 = (~in_6_0[2] & ~in_6_0[4] & in_6_0[6]);
    wire w_sh6 = (in_6_0[3] & in_6_0[6]);
    wire [6:0] opcode = instr[6:0];
    wire [2:0] funct3 = instr[14:12];
    wire funct7b5 = instr[30];
    wire [3:0] _alu_op;
    assign _alu_op = {(~in_6_0[2] & ~in_6_0[6] & in_14_12[1] & in_14_12[2]) | w_sh3, (~in_6_0[2] & in_14_12[0] & in_14_12[1] & ~in_14_12[2]) | (~in_6_0[2] & in_6_0[4] & ~in_14_12[1] & in_14_12[2]) | w_sh1 | (~in_6_0[2] & in_6_0[6] & in_14_12[1]), w_sh0 | (~in_6_0[2] & in_6_0[4] & in_14_12[0] & ~in_14_12[1]) | w_sh2 | w_sh3, (~in_6_0[2] & in_6_0[4] & in_6_0[5] & ~in_6_0[6] & in_30_30) | w_sh0 | (~in_6_0[2] & ~in_6_0[6] & in_14_12[0] & in_14_12[1] & in_14_12[2]) | (~in_6_0[2] & in_6_0[4] & ~in_14_12[0] & ~in_14_12[1] & in_14_12[2]) | (~in_6_0[2] & in_6_0[4] & ~in_14_12[1] & in_14_12[2] & in_30_30) | w_sh1 | w_sh2};
    wire [2:0] _imm_sel;
    assign _imm_sel = {(in_6_0[2] & in_6_0[4]) | w_sh6, w_sh4 | w_sh5, (~in_6_0[2] & ~in_6_0[5]) | (~in_6_0[4] & in_6_0[6])};
    wire _use_rs1;
    assign _use_rs1 = (~in_6_0[2] & ~in_6_0[6]) | (~in_6_0[3] & ~in_6_0[4]);
    wire _use_rs2;
    assign _use_rs2 = (~in_6_0[2] & in_6_0[5] & ~in_6_0[6]) | w_sh5;
    wire _use_rd;
    assign _use_rd = (in_6_0[4] & ~in_6_0[6]) | (~in_6_0[3] & ~in_6_0[5]) | (in_6_0[2] & in_6_0[6]);
    wire _is_load;
    assign _is_load = (~in_6_0[3] & ~in_6_0[4] & ~in_6_0[5]);
    wire _is_store;
    assign _is_store = w_sh4;
    wire _is_branch;
    assign _is_branch = w_sh5;
    wire _is_jal;
    assign _is_jal = w_sh6;
    wire _is_jalr;
    assign _is_jalr = (in_6_0[2] & ~in_6_0[3] & in_6_0[6]);
    wire [1:0] _mem_width;
    assign _mem_width = {(~in_6_0[4] & ~in_6_0[6] & in_14_12[1]), (~in_6_0[4] & ~in_6_0[6] & in_14_12[0])};
    wire _mem_signed;
    assign _mem_signed = (~in_6_0[3] & ~in_6_0[4] & ~in_6_0[5] & ~in_14_12[1] & ~in_14_12[2]);

    // Connect internal wires to output ports.
    assign alu_op = _alu_op;
    assign imm_sel = _imm_sel;
    assign use_rs1 = _use_rs1;
    assign use_rs2 = _use_rs2;
    assign use_rd = _use_rd;
    assign is_load = _is_load;
    assign is_store = _is_store;
    assign is_branch = _is_branch;
    assign is_jal = _is_jal;
    assign is_jalr = _is_jalr;
    assign mem_width = _mem_width;
    assign mem_signed = _mem_signed;

endmodule
