// RISC-V RV32I instruction decode — hand-coded case statement.
//
// This is the RTL a competent engineer would write on first pass:
//   - Nested case on {funct7b5, funct3} inside each opcode group.
//   - Default assignments at the top of the always_comb to prevent latches.
//   - No manual Karnaugh-map optimisation — outputs are assigned once per arm.
//
// This file exists as a comparison baseline for synth_compare.py.
// The constraint-synthesized version (rv32i_decode.sv) is generated by
// ConstraintCompiler and compared against this on cell count and logic depth.
//
// ALU operation encoding (matches rv32i_decode.py)
`define ALU_ADD  4'd0
`define ALU_SUB  4'd1
`define ALU_SLL  4'd2
`define ALU_SLT  4'd3
`define ALU_SLTU 4'd4
`define ALU_XOR  4'd5
`define ALU_SRL  4'd6
`define ALU_SRA  4'd7
`define ALU_OR   4'd8
`define ALU_AND  4'd9
`define ALU_PASS 4'd10

// Immediate format encoding
`define IMM_NONE 3'd0
`define IMM_I    3'd1
`define IMM_S    3'd2
`define IMM_B    3'd3
`define IMM_U    3'd4
`define IMM_J    3'd5

module rv32i_decode_manual (
    input  logic [31:0] instr,
    output logic [3:0]  alu_op,
    output logic [2:0]  imm_sel,
    output logic        use_rs1,
    output logic        use_rs2,
    output logic        use_rd,
    output logic        is_load,
    output logic        is_store,
    output logic        is_branch,
    output logic        is_jal,
    output logic        is_jalr,
    output logic [1:0]  mem_width,
    output logic        mem_signed
);

    logic [6:0] opcode;
    logic [2:0] funct3;
    logic       funct7b5;

    assign opcode   = instr[6:0];
    assign funct3   = instr[14:12];
    assign funct7b5 = instr[30];

    always_comb begin
        // Defaults — every output driven on every path; prevents synthesis latches.
        alu_op    = `ALU_ADD;
        imm_sel   = `IMM_NONE;
        use_rs1   = 1'b0;
        use_rs2   = 1'b0;
        use_rd    = 1'b0;
        is_load   = 1'b0;
        is_store  = 1'b0;
        is_branch = 1'b0;
        is_jal    = 1'b0;
        is_jalr   = 1'b0;
        mem_width  = 2'd0;
        mem_signed = 1'b0;

        case (opcode)

            // ------------------------------------------------------------------
            // R-type: opcode = 7'h33
            // ------------------------------------------------------------------
            7'h33: begin
                use_rs1 = 1'b1;
                use_rs2 = 1'b1;
                use_rd  = 1'b1;
                imm_sel = `IMM_NONE;
                case ({funct7b5, funct3})
                    4'b0_000: alu_op = `ALU_ADD;
                    4'b1_000: alu_op = `ALU_SUB;
                    4'b0_001: alu_op = `ALU_SLL;
                    4'b0_010: alu_op = `ALU_SLT;
                    4'b0_011: alu_op = `ALU_SLTU;
                    4'b0_100: alu_op = `ALU_XOR;
                    4'b0_101: alu_op = `ALU_SRL;
                    4'b1_101: alu_op = `ALU_SRA;
                    4'b0_110: alu_op = `ALU_OR;
                    4'b0_111: alu_op = `ALU_AND;
                    default:  alu_op = `ALU_ADD;
                endcase
            end

            // ------------------------------------------------------------------
            // I-type ALU: opcode = 7'h13
            // ------------------------------------------------------------------
            7'h13: begin
                use_rs1 = 1'b1;
                use_rs2 = 1'b0;
                use_rd  = 1'b1;
                imm_sel = `IMM_I;
                case (funct3)
                    3'b000: alu_op = `ALU_ADD;
                    3'b001: alu_op = `ALU_SLL;   // SLLI (funct7b5=0 implied)
                    3'b010: alu_op = `ALU_SLT;
                    3'b011: alu_op = `ALU_SLTU;
                    3'b100: alu_op = `ALU_XOR;
                    3'b101: alu_op = (funct7b5) ? `ALU_SRA : `ALU_SRL;
                    3'b110: alu_op = `ALU_OR;
                    3'b111: alu_op = `ALU_AND;
                    default: alu_op = `ALU_ADD;
                endcase
            end

            // ------------------------------------------------------------------
            // Load: opcode = 7'h03
            // ------------------------------------------------------------------
            7'h03: begin
                alu_op  = `ALU_ADD;
                imm_sel = `IMM_I;
                use_rs1 = 1'b1;
                use_rs2 = 1'b0;
                use_rd  = 1'b1;
                is_load = 1'b1;
                case (funct3)
                    3'b000: begin mem_width = 2'd0; mem_signed = 1'b1; end  // LB
                    3'b001: begin mem_width = 2'd1; mem_signed = 1'b1; end  // LH
                    3'b010: begin mem_width = 2'd2; mem_signed = 1'b0; end  // LW (full 32-bit; no extension)
                    3'b100: begin mem_width = 2'd0; mem_signed = 1'b0; end  // LBU
                    3'b101: begin mem_width = 2'd1; mem_signed = 1'b0; end  // LHU
                    default: begin mem_width = 2'd0; mem_signed = 1'b0; end
                endcase
            end

            // ------------------------------------------------------------------
            // Store: opcode = 7'h23
            // ------------------------------------------------------------------
            7'h23: begin
                alu_op   = `ALU_ADD;
                imm_sel  = `IMM_S;
                use_rs1  = 1'b1;
                use_rs2  = 1'b1;
                use_rd   = 1'b0;
                is_store = 1'b1;
                case (funct3)
                    3'b000: mem_width = 2'd0;  // SB
                    3'b001: mem_width = 2'd1;  // SH
                    3'b010: mem_width = 2'd2;  // SW
                    default: mem_width = 2'd0;
                endcase
            end

            // ------------------------------------------------------------------
            // Branch: opcode = 7'h63
            // ------------------------------------------------------------------
            7'h63: begin
                imm_sel   = `IMM_B;
                use_rs1   = 1'b1;
                use_rs2   = 1'b1;
                use_rd    = 1'b0;
                is_branch = 1'b1;
                case (funct3)
                    3'b000: alu_op = `ALU_XOR;   // BEQ
                    3'b001: alu_op = `ALU_XOR;   // BNE
                    3'b100: alu_op = `ALU_SLT;   // BLT
                    3'b101: alu_op = `ALU_SLT;   // BGE
                    3'b110: alu_op = `ALU_SLTU;  // BLTU
                    3'b111: alu_op = `ALU_SLTU;  // BGEU
                    default: alu_op = `ALU_XOR;
                endcase
            end

            // ------------------------------------------------------------------
            // LUI: opcode = 7'h37
            // ------------------------------------------------------------------
            7'h37: begin
                alu_op  = `ALU_PASS;
                imm_sel = `IMM_U;
                use_rs1 = 1'b0;
                use_rs2 = 1'b0;
                use_rd  = 1'b1;
            end

            // ------------------------------------------------------------------
            // AUIPC: opcode = 7'h17
            // ------------------------------------------------------------------
            7'h17: begin
                alu_op  = `ALU_ADD;
                imm_sel = `IMM_U;
                use_rs1 = 1'b0;
                use_rs2 = 1'b0;
                use_rd  = 1'b1;
            end

            // ------------------------------------------------------------------
            // JAL: opcode = 7'h6F
            // ------------------------------------------------------------------
            7'h6F: begin
                alu_op  = `ALU_ADD;
                imm_sel = `IMM_J;
                use_rs1 = 1'b0;
                use_rs2 = 1'b0;
                use_rd  = 1'b1;
                is_jal  = 1'b1;
            end

            // ------------------------------------------------------------------
            // JALR: opcode = 7'h67
            // ------------------------------------------------------------------
            7'h67: begin
                alu_op  = `ALU_ADD;
                imm_sel = `IMM_I;
                use_rs1 = 1'b1;
                use_rs2 = 1'b0;
                use_rd  = 1'b1;
                is_jalr = 1'b1;
            end

            // ------------------------------------------------------------------
            // FENCE / SYSTEM: opcode = 7'h0F / 7'h73 — decode only; NOP outputs.
            // ------------------------------------------------------------------
            7'h0F, 7'h73: begin
                alu_op  = `ALU_ADD;
                imm_sel = `IMM_NONE;
            end

            // ------------------------------------------------------------------
            // Unknown opcode — all outputs remain at defaults (safe NOP).
            // ------------------------------------------------------------------
            default: begin
                // defaults already applied above
            end

        endcase
    end

endmodule
